# Generated by Django 4.0.2 on 2022-02-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='GOOD BLOG', max_length=255),
        ),
    ]
