# Generated by Django 4.0.2 on 2022-02-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryblog', '0003_post_publication_date_alter_post_title_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='coding', max_length=255),
        ),
    ]
