# Generated by Django 4.0.2 on 2022-04-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryblog', '0010_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='college_name',
            field=models.CharField(default='not an college', max_length=255),
        ),
    ]
