# Generated by Django 4.0.2 on 2022-04-16 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryblog', '0011_post_college_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
