# Generated by Django 4.0.2 on 2022-04-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryblog', '0013_alter_post_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='college_name',
            field=models.CharField(max_length=255),
        ),
    ]
