# Generated by Django 4.0.2 on 2022-04-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryblog', '0014_alter_post_college_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='register_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images/profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
